version: '3.3'

services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=sudhakar
      - MYSQL_USER=lollipop
      - MYSQL_PASSWORD=password

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=lollipop
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=sudhakar

volumes:
  db_data: